# Generated by Django 3.2.2 on 2021-05-08 14:37

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('bookmarks', store.models.JSONField(blank=True, default={'books': [], 'total': 0}, null=True)),
            ],
        ),
    ]
